export type LibraryType = 'public' | 'private' | 'little'

export type Province = 
  | 'AB' | 'BC' | 'MB' | 'NB' | 'NL' | 'NS' | 'NT' | 'NU' 
  | 'ON' | 'PE' | 'QC' | 'SK' | 'YT'

export type LibraryService = 
  | 'wifi' | 'printing' | 'computers' | 'meeting-rooms' | 'study-rooms'
  | 'programs' | 'children' | 'digital-resources' | 'makerspace'
  | '3d-printing' | 'streaming' | 'language-learning' | 'job-search'
  | 'accessibility' | 'parking' | 'cafe' | 'museum-passes'

export interface Library {
  id: string
  name: string
  type: LibraryType
  province: Province
  region: string
  address: string
  city: string
  postalCode: string
  phone: string
  website: string
  latitude: number
  longitude: number
  photoUrl?: string
  services?: LibraryService[]
}

export const provinceNames: Record<Province, string> = {
  'AB': 'Alberta',
  'BC': 'British Columbia',
  'MB': 'Manitoba',
  'NB': 'New Brunswick',
  'NL': 'Newfoundland and Labrador',
  'NS': 'Nova Scotia',
  'NT': 'Northwest Territories',
  'NU': 'Nunavut',
  'ON': 'Ontario',
  'PE': 'Prince Edward Island',
  'QC': 'Quebec',
  'SK': 'Saskatchewan',
  'YT': 'Yukon'
}

export const libraries: Library[] = [
  {
    id: 'fvrl-abbotsford',
    name: 'Abbotsford Library',
    type: 'public',
    province: 'BC',
    region: 'Fraser Valley',
    address: '33660 South Fraser Way',
    city: 'Abbotsford',
    postalCode: 'V2S 2C5',
    phone: '604-859-7814',
    website: 'https://www.fvrl.bc.ca/branches/abbotsford',
    latitude: 49.0504,
    longitude: -122.2988,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'fvrl-agassiz',
    name: 'Agassiz Library',
    type: 'public',
    province: 'BC',
    region: 'Fraser Valley',
    address: '7111 Cheam Avenue',
    city: 'Agassiz',
    postalCode: 'V0M 1A0',
    phone: '604-796-9756',
    website: 'https://www.fvrl.bc.ca/branches/agassiz',
    latitude: 49.2378,
    longitude: -121.7617,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'fvrl-chilliwack',
    name: 'Chilliwack Library',
    type: 'public',
    province: 'BC',
    region: 'Fraser Valley',
    address: '45860 First Avenue',
    city: 'Chilliwack',
    postalCode: 'V2P 7K1',
    phone: '604-792-4450',
    website: 'https://www.fvrl.bc.ca/branches/chilliwack',
    latitude: 49.1577,
    longitude: -121.9509,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', 'accessibility', 'parking']
  },
  {
    id: 'vpl-central',
    name: 'Vancouver Central Library',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '350 West Georgia Street',
    city: 'Vancouver',
    postalCode: 'V6B 6B1',
    phone: '604-331-3603',
    website: 'https://www.vpl.ca/branches/central-library',
    latitude: 49.2799,
    longitude: -123.1158,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', '3d-printing', 'streaming', 'language-learning', 'job-search', 'accessibility', 'cafe', 'museum-passes']
  },
  {
    id: 'tpl-reference',
    name: 'Toronto Reference Library',
    type: 'public',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '789 Yonge Street',
    city: 'Toronto',
    postalCode: 'M4W 2G8',
    phone: '416-395-5577',
    website: 'https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC&R=LIB002',
    latitude: 43.6719,
    longitude: -79.3863,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', '3d-printing', 'streaming', 'language-learning', 'job-search', 'accessibility', 'cafe', 'museum-passes']
  },
  {
    id: 'epl-stanley-milner',
    name: 'Stanley A. Milner Library',
    type: 'public',
    province: 'AB',
    region: 'Edmonton',
    address: '7 Sir Winston Churchill Square',
    city: 'Edmonton',
    postalCode: 'T5J 2V4',
    phone: '780-496-7000',
    website: 'https://www.epl.ca/stanley-milner/',
    latitude: 53.5444,
    longitude: -113.4909,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', '3d-printing', 'streaming', 'language-learning', 'job-search', 'accessibility', 'parking', 'museum-passes']
  },
  {
    id: 'cpl-central',
    name: 'Calgary Central Library',
    type: 'public',
    province: 'AB',
    region: 'Calgary',
    address: '800 3 Street SE',
    city: 'Calgary',
    postalCode: 'T2G 2E7',
    phone: '403-260-2600',
    website: 'https://calgarylibrary.ca/visit/our-locations/central-library/',
    latitude: 51.0447,
    longitude: -114.0545,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', '3d-printing', 'streaming', 'language-learning', 'job-search', 'accessibility', 'cafe', 'museum-passes']
  },
  {
    id: 'bpl-millennium',
    name: 'Bibliothèque et Archives nationales du Québec',
    type: 'public',
    province: 'QC',
    region: 'Montreal',
    address: '475 Boulevard De Maisonneuve E',
    city: 'Montreal',
    postalCode: 'H2L 5C4',
    phone: '514-873-1100',
    website: 'https://www.banq.qc.ca/',
    latitude: 45.5155,
    longitude: -73.5615,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'streaming', 'language-learning', 'accessibility', 'cafe']
  },
  {
    id: 'wpl-central',
    name: 'Winnipeg Millennium Library',
    type: 'public',
    province: 'MB',
    region: 'Winnipeg',
    address: '251 Donald Street',
    city: 'Winnipeg',
    postalCode: 'R3C 3P5',
    phone: '204-986-6450',
    website: 'https://wpl.winnipeg.ca/library/branches/millennium.asp',
    latitude: 49.8880,
    longitude: -97.1395,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'language-learning', 'job-search', 'accessibility', 'parking', 'museum-passes']
  },
  {
    id: 'hpl-central',
    name: 'Halifax Central Library',
    type: 'public',
    province: 'NS',
    region: 'Halifax',
    address: '5440 Spring Garden Road',
    city: 'Halifax',
    postalCode: 'B3J 1E9',
    phone: '902-490-5700',
    website: 'https://www.halifaxpubliclibraries.ca/locations/central-library/',
    latitude: 44.6434,
    longitude: -63.5797,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', '3d-printing', 'streaming', 'language-learning', 'job-search', 'accessibility', 'cafe', 'museum-passes']
  },
  {
    id: 'opl-main',
    name: 'Ottawa Public Library Main Branch',
    type: 'public',
    province: 'ON',
    region: 'Ottawa',
    address: '120 Metcalfe Street',
    city: 'Ottawa',
    postalCode: 'K1P 5M2',
    phone: '613-580-2940',
    website: 'https://biblioottawalibrary.ca/en/main',
    latitude: 45.4215,
    longitude: -75.6972,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', 'streaming', 'language-learning', 'job-search', 'accessibility', 'museum-passes']
  },
  {
    id: 'spl-central',
    name: 'Saskatoon Public Library - Frances Morrison',
    type: 'public',
    province: 'SK',
    region: 'Saskatoon',
    address: '311 23rd Street East',
    city: 'Saskatoon',
    postalCode: 'S7K 0J6',
    phone: '306-975-7558',
    website: 'https://saskatoonlibrary.ca/locations/frances-morrison-central-library',
    latitude: 52.1279,
    longitude: -106.6702,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'language-learning', 'job-search', 'accessibility', 'parking']
  },
  {
    id: 'rpl-central',
    name: 'Regina Public Library - Central Branch',
    type: 'public',
    province: 'SK',
    region: 'Regina',
    address: '2311 12th Avenue',
    city: 'Regina',
    postalCode: 'S4P 3Z5',
    phone: '306-777-6000',
    website: 'https://www.reginalibrary.ca/visit/locations/central',
    latitude: 50.4501,
    longitude: -104.6178,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'language-learning', 'job-search', 'accessibility', 'parking']
  },
  {
    id: 'little-vancouver-1',
    name: 'Little Free Library - Kitsilano Beach',
    type: 'little',
    province: 'BC',
    region: 'Metro Vancouver',
    address: 'Cornwall Avenue at Yew Street',
    city: 'Vancouver',
    postalCode: 'V6K 2E9',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 49.2734,
    longitude: -123.1534,
    services: []
  },
  {
    id: 'little-toronto-1',
    name: 'Little Free Library - High Park',
    type: 'little',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: 'High Park Avenue near Bloor Street',
    city: 'Toronto',
    postalCode: 'M6P 2S3',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 43.6532,
    longitude: -79.4636,
    services: []
  },
  {
    id: 'uvic-library',
    name: 'University of Victoria Libraries',
    type: 'private',
    province: 'BC',
    region: 'Victoria',
    address: '3800 Finnerty Road',
    city: 'Victoria',
    postalCode: 'V8P 5C2',
    phone: '250-721-6673',
    website: 'https://www.uvic.ca/library/',
    latitude: 48.4634,
    longitude: -123.3117,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'study-rooms', 'digital-resources', 'accessibility']
  },
  {
    id: 'ubc-library',
    name: 'UBC Library',
    type: 'private',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '1961 East Mall',
    city: 'Vancouver',
    postalCode: 'V6T 1Z1',
    phone: '604-822-3200',
    website: 'https://www.library.ubc.ca/',
    latitude: 49.2676,
    longitude: -123.2532,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'study-rooms', 'digital-resources', 'makerspace', 'accessibility', 'cafe']
  },
  {
    id: 'mcgill-library',
    name: 'McGill University Library',
    type: 'private',
    province: 'QC',
    region: 'Montreal',
    address: '845 Sherbrooke Street West',
    city: 'Montreal',
    postalCode: 'H3A 0G4',
    phone: '514-398-4734',
    website: 'https://www.mcgill.ca/library/',
    latitude: 45.5048,
    longitude: -73.5772,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'study-rooms', 'digital-resources', 'accessibility']
  },
  {
    id: 'uoft-robarts',
    name: 'Robarts Library - University of Toronto',
    type: 'private',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '130 St. George Street',
    city: 'Toronto',
    postalCode: 'M5S 1A5',
    phone: '416-978-7344',
    website: 'https://onesearch.library.utoronto.ca/robarts',
    latitude: 43.6644,
    longitude: -79.3997,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'study-rooms', 'digital-resources', 'accessibility', 'cafe']
  },
  {
    id: 'vpl-hastings',
    name: 'Hastings Branch - Vancouver Public Library',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '3350 Victoria Drive',
    city: 'Vancouver',
    postalCode: 'V5N 4M5',
    phone: '604-665-3970',
    website: 'https://www.vpl.ca/branches/hastings-branch',
    latitude: 49.2427,
    longitude: -123.0614,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'vpl-kerrisdale',
    name: 'Kerrisdale Branch - Vancouver Public Library',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '2112 West 42nd Avenue',
    city: 'Vancouver',
    postalCode: 'V6M 2B7',
    phone: '604-665-3970',
    website: 'https://www.vpl.ca/branches/kerrisdale-branch',
    latitude: 49.2334,
    longitude: -123.1598,
    photoUrl: '',
    services: ['wifi', 'printing', 'computers', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'bpl-westmount',
    name: 'Westmount Public Library',
    type: 'public',
    province: 'QC',
    region: 'Montreal',
    address: '4574 Sherbrooke Street West',
    city: 'Westmount',
    postalCode: 'H3Z 1E9',
    phone: '514-989-5300',
    website: 'https://www.westlib.org/',
    latitude: 45.4839,
    longitude: -73.5927
  },
  {
    id: 'bpl-vieux-montreal',
    name: 'Bibliothèque Frontenac',
    type: 'public',
    province: 'QC',
    region: 'Montreal',
    address: '2550 Ontario Street East',
    city: 'Montreal',
    postalCode: 'H2K 1W7',
    phone: '514-872-7888',
    website: 'https://montreal.biblio.pretnumerique.ca/branches/frontenac',
    latitude: 45.5297,
    longitude: -73.5529
  },
  {
    id: 'spl-lakeview',
    name: 'Lakeview Branch - Saskatoon Public Library',
    type: 'public',
    province: 'SK',
    region: 'Saskatoon',
    address: '100 - 7th Street East',
    city: 'Saskatoon',
    postalCode: 'S7H 0V9',
    phone: '306-975-7581',
    website: 'https://saskatoonlibrary.ca/locations/lakeview',
    latitude: 52.1169,
    longitude: -106.6267
  },
  {
    id: 'rpl-southland',
    name: 'Southland Branch - Regina Public Library',
    type: 'public',
    province: 'SK',
    region: 'Regina',
    address: '4835 Parliament Avenue',
    city: 'Regina',
    postalCode: 'S4W 0R4',
    phone: '306-777-6189',
    website: 'https://www.reginalibrary.ca/visit/locations/southland',
    latitude: 50.4172,
    longitude: -104.6298
  },
  {
    id: 'cpl-saddletowne',
    name: 'Saddletowne Library - Calgary Public Library',
    type: 'public',
    province: 'AB',
    region: 'Calgary',
    address: '100 Saddletowne Circle NE',
    city: 'Calgary',
    postalCode: 'T3J 0C9',
    phone: '403-260-2600',
    website: 'https://calgarylibrary.ca/visit/our-locations/saddletowne/',
    latitude: 51.1371,
    longitude: -113.9568
  },
  {
    id: 'cpl-crowfoot',
    name: 'Crowfoot Library - Calgary Public Library',
    type: 'public',
    province: 'AB',
    region: 'Calgary',
    address: '8665 Nose Hill Drive NW',
    city: 'Calgary',
    postalCode: 'T3G 5T3',
    phone: '403-260-2600',
    website: 'https://calgarylibrary.ca/visit/our-locations/crowfoot/',
    latitude: 51.1209,
    longitude: -114.1743
  },
  {
    id: 'epl-clareview',
    name: 'Clareview Community Library - Edmonton Public Library',
    type: 'public',
    province: 'AB',
    region: 'Edmonton',
    address: '14835 38 Street NW',
    city: 'Edmonton',
    postalCode: 'T5Y 3G3',
    phone: '780-496-1806',
    website: 'https://www.epl.ca/clareview/',
    latitude: 53.5878,
    longitude: -113.3888
  },
  {
    id: 'epl-whitemud-crossing',
    name: 'Whitemud Crossing Library - Edmonton Public Library',
    type: 'public',
    province: 'AB',
    region: 'Edmonton',
    address: '145 Whitemud Crossing Shopping Centre',
    city: 'Edmonton',
    postalCode: 'T6H 4P1',
    phone: '780-496-7090',
    website: 'https://www.epl.ca/whitemud-crossing/',
    latitude: 53.4726,
    longitude: -113.5228
  },
  {
    id: 'tpl-scarborough',
    name: 'Scarborough Civic Centre Library',
    type: 'public',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '150 Borough Drive',
    city: 'Scarborough',
    postalCode: 'M1P 4N7',
    phone: '416-396-8943',
    website: 'https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC&R=LIB131',
    latitude: 43.7748,
    longitude: -79.2572
  },
  {
    id: 'tpl-north-york',
    name: 'North York Central Library',
    type: 'public',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '5120 Yonge Street',
    city: 'North York',
    postalCode: 'M2N 5N9',
    phone: '416-395-5535',
    website: 'https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC&R=LIB100',
    latitude: 43.7676,
    longitude: -79.4123
  },
  {
    id: 'tpl-fort-york',
    name: 'Fort York Library',
    type: 'public',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '190 Fort York Boulevard',
    city: 'Toronto',
    postalCode: 'M5V 0E3',
    phone: '416-393-7480',
    website: 'https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC&R=LIB087',
    latitude: 43.6386,
    longitude: -79.4019
  },
  {
    id: 'wpl-cornish',
    name: 'Cornish Library - Winnipeg Public Library',
    type: 'public',
    province: 'MB',
    region: 'Winnipeg',
    address: '20 West Gate',
    city: 'Winnipeg',
    postalCode: 'R3C 2E2',
    phone: '204-986-4806',
    website: 'https://wpl.winnipeg.ca/library/branches/cornish.asp',
    latitude: 49.8995,
    longitude: -97.1686
  },
  {
    id: 'wpl-henderson',
    name: 'Henderson Library - Winnipeg Public Library',
    type: 'public',
    province: 'MB',
    region: 'Winnipeg',
    address: '1050 Henderson Highway',
    city: 'Winnipeg',
    postalCode: 'R2K 2M5',
    phone: '204-986-4773',
    website: 'https://wpl.winnipeg.ca/library/branches/henderson.asp',
    latitude: 49.9248,
    longitude: -97.0768
  },
  {
    id: 'hpl-dartmouth',
    name: 'Dartmouth North Library - Halifax Public Libraries',
    type: 'public',
    province: 'NS',
    region: 'Halifax',
    address: '3 Chappell Street',
    city: 'Dartmouth',
    postalCode: 'B2Y 4M8',
    phone: '902-490-5723',
    website: 'https://www.halifaxpubliclibraries.ca/locations/dartmouth-north/',
    latitude: 44.6933,
    longitude: -63.5724
  },
  {
    id: 'hpl-sackville',
    name: 'Sackville Library - Halifax Public Libraries',
    type: 'public',
    province: 'NS',
    region: 'Halifax',
    address: '636 Sackville Drive',
    city: 'Lower Sackville',
    postalCode: 'B4C 2S4',
    phone: '902-490-5723',
    website: 'https://www.halifaxpubliclibraries.ca/locations/sackville/',
    latitude: 44.7705,
    longitude: -63.6827
  },
  {
    id: 'nbpl-fredericton',
    name: 'Fredericton Public Library',
    type: 'public',
    province: 'NB',
    region: 'Fredericton',
    address: '12 Carleton Street',
    city: 'Fredericton',
    postalCode: 'E3B 3T4',
    phone: '506-460-2800',
    website: 'https://www.gnb.ca/publiclibraries',
    latitude: 45.9636,
    longitude: -66.6431
  },
  {
    id: 'nbpl-moncton',
    name: 'Moncton Public Library',
    type: 'public',
    province: 'NB',
    region: 'Greater Moncton',
    address: '644 Main Street',
    city: 'Moncton',
    postalCode: 'E1C 1E2',
    phone: '506-869-6000',
    website: 'https://www.moncton.ca/Government/City_Departments/Recreation_Culture_and_Events/Programs_and_Activities/Library.htm',
    latitude: 46.0878,
    longitude: -64.7782
  },
  {
    id: 'nbpl-saint-john',
    name: 'Saint John Free Public Library',
    type: 'public',
    province: 'NB',
    region: 'Saint John',
    address: '1 Market Square',
    city: 'Saint John',
    postalCode: 'E2L 4Z6',
    phone: '506-643-7220',
    website: 'https://saintjohnfpl.ca/',
    latitude: 45.2733,
    longitude: -66.0633
  },
  {
    id: 'nlpl-a-c-hunter',
    name: 'A.C. Hunter Public Library',
    type: 'public',
    province: 'NL',
    region: "St. John's",
    address: '48 Hayward Avenue',
    city: "St. John's",
    postalCode: 'A1E 1V5',
    phone: '709-737-3955',
    website: 'https://www.nlpl.ca/branches/st-johns-public-library',
    latitude: 47.5615,
    longitude: -52.7126
  },
  {
    id: 'nlpl-corner-brook',
    name: 'Corner Brook Public Library',
    type: 'public',
    province: 'NL',
    region: 'Corner Brook',
    address: '39 West Street',
    city: 'Corner Brook',
    postalCode: 'A2H 2Y9',
    phone: '709-634-0013',
    website: 'https://www.nlpl.ca/branches/corner-brook-public-library',
    latitude: 48.9481,
    longitude: -57.9528
  },
  {
    id: 'peipl-charlottetown',
    name: 'Confederation Centre Public Library',
    type: 'public',
    province: 'PE',
    region: 'Charlottetown',
    address: '145 Richmond Street',
    city: 'Charlottetown',
    postalCode: 'C1A 1J1',
    phone: '902-368-4642',
    website: 'https://www.library.pe.ca/',
    latitude: 46.2382,
    longitude: -63.1311
  },
  {
    id: 'peipl-summerside',
    name: 'Rotary Library - Summerside',
    type: 'public',
    province: 'PE',
    region: 'Summerside',
    address: '192 Water Street',
    city: 'Summerside',
    postalCode: 'C1N 1B1',
    phone: '902-888-8405',
    website: 'https://www.library.pe.ca/summerside',
    latitude: 46.3956,
    longitude: -63.7891
  },
  {
    id: 'ykpl-whitehorse',
    name: 'Whitehorse Public Library',
    type: 'public',
    province: 'YT',
    region: 'Whitehorse',
    address: '2071 Second Avenue',
    city: 'Whitehorse',
    postalCode: 'Y1A 1B8',
    phone: '867-667-5239',
    website: 'https://www.whitehorselibrary.ca/',
    latitude: 60.7212,
    longitude: -135.0568
  },
  {
    id: 'ykpl-dawson-city',
    name: 'Dawson City Community Library',
    type: 'public',
    province: 'YT',
    region: 'Dawson City',
    address: '5th Avenue',
    city: 'Dawson City',
    postalCode: 'Y0B 1G0',
    phone: '867-993-5571',
    website: 'https://yukoncommunitylibraries.ca/dawson-city/',
    latitude: 64.0604,
    longitude: -139.4304
  },
  {
    id: 'ntpl-yellowknife',
    name: 'Yellowknife Public Library',
    type: 'public',
    province: 'NT',
    region: 'Yellowknife',
    address: '5022 49th Street',
    city: 'Yellowknife',
    postalCode: 'X1A 1P3',
    phone: '867-920-5642',
    website: 'https://www.yellowknifelibrary.ca/',
    latitude: 62.4540,
    longitude: -114.3718
  },
  {
    id: 'ntpl-inuvik',
    name: 'Inuvik Centennial Library',
    type: 'public',
    province: 'NT',
    region: 'Inuvik',
    address: '100 Mackenzie Road',
    city: 'Inuvik',
    postalCode: 'X0E 0T0',
    phone: '867-777-8650',
    website: 'https://www.inuvik.ca/en/living-here/centennial-library.aspx',
    latitude: 68.3607,
    longitude: -133.7230
  },
  {
    id: 'nupl-iqaluit',
    name: 'Iqaluit Centennial Library',
    type: 'public',
    province: 'NU',
    region: 'Iqaluit',
    address: 'Niaqunnguuq Building',
    city: 'Iqaluit',
    postalCode: 'X0A 0H0',
    phone: '867-979-5400',
    website: 'https://www.iqaluitlibrary.ca/',
    latitude: 63.7467,
    longitude: -68.5170
  },
  {
    id: 'opl-rideau',
    name: 'Rideau Branch - Ottawa Public Library',
    type: 'public',
    province: 'ON',
    region: 'Ottawa',
    address: '377 Rideau Street',
    city: 'Ottawa',
    postalCode: 'K1N 5Y7',
    phone: '613-580-2940',
    website: 'https://biblioottawalibrary.ca/en/rideau',
    latitude: 45.4286,
    longitude: -75.6845
  },
  {
    id: 'opl-nepean-centrepointe',
    name: 'Nepean Centrepointe - Ottawa Public Library',
    type: 'public',
    province: 'ON',
    region: 'Ottawa',
    address: '101 Centrepointe Drive',
    city: 'Ottawa',
    postalCode: 'K2G 5K7',
    phone: '613-580-2940',
    website: 'https://biblioottawalibrary.ca/en/nepean-centrepointe',
    latitude: 45.3255,
    longitude: -75.7634
  },
  {
    id: 'hwpl-hamilton-central',
    name: 'Hamilton Public Library - Central',
    type: 'public',
    province: 'ON',
    region: 'Hamilton',
    address: '55 York Boulevard',
    city: 'Hamilton',
    postalCode: 'L8N 4E4',
    phone: '905-546-3200',
    website: 'https://www.hpl.ca/locations/central',
    latitude: 43.2557,
    longitude: -79.8711
  },
  {
    id: 'hwpl-hamilton-terryberry',
    name: 'Terryberry Branch - Hamilton Public Library',
    type: 'public',
    province: 'ON',
    region: 'Hamilton',
    address: '200 Mohawk Road East',
    city: 'Hamilton',
    postalCode: 'L9A 2G4',
    phone: '905-546-3406',
    website: 'https://www.hpl.ca/locations/terryberry',
    latitude: 43.2271,
    longitude: -79.8311
  },
  {
    id: 'kwpl-kitchener-central',
    name: 'Kitchener Public Library - Central',
    type: 'public',
    province: 'ON',
    region: 'Waterloo Region',
    address: '85 Queen Street North',
    city: 'Kitchener',
    postalCode: 'N2H 2H1',
    phone: '519-743-0271',
    website: 'https://www.kpl.org/locations/kitchener-central-library',
    latitude: 43.4516,
    longitude: -80.4925
  },
  {
    id: 'lpl-london-central',
    name: 'London Public Library - Central',
    type: 'public',
    province: 'ON',
    region: 'London',
    address: '251 Dundas Street',
    city: 'London',
    postalCode: 'N6A 6H9',
    phone: '519-661-4600',
    website: 'https://www.londonpubliclibrary.ca/locations/central',
    latitude: 42.9849,
    longitude: -81.2453
  },
  {
    id: 'bpl-quebec-gabrielle-roy',
    name: 'Bibliothèque Gabrielle-Roy',
    type: 'public',
    province: 'QC',
    region: 'Quebec City',
    address: '350 Rue Saint-Joseph Est',
    city: 'Quebec City',
    postalCode: 'G1K 3B2',
    phone: '418-641-6789',
    website: 'https://www.bibliothequesdequebec.qc.ca/bibliotheques/gabrielle-roy',
    latitude: 46.8139,
    longitude: -71.2264
  },
  {
    id: 'bpl-quebec-monique-corriveau',
    name: 'Bibliothèque Monique-Corriveau',
    type: 'public',
    province: 'QC',
    region: 'Quebec City',
    address: '8400 Avenue du Marais',
    city: 'Quebec City',
    postalCode: 'G1G 6M8',
    phone: '418-641-6789',
    website: 'https://www.bibliothequesdequebec.qc.ca/bibliotheques/monique-corriveau',
    latitude: 46.8598,
    longitude: -71.2698
  },
  {
    id: 'bpl-laval-multiculturelle',
    name: 'Bibliothèque multiculturelle de Laval',
    type: 'public',
    province: 'QC',
    region: 'Laval',
    address: '6540 Boulevard Lévesque Est',
    city: 'Laval',
    postalCode: 'H7C 1K7',
    phone: '450-978-5959',
    website: 'https://www.bibliomulticulturelles.ca/',
    latitude: 45.5992,
    longitude: -73.5043
  },
  {
    id: 'bpl-gatineau-hull',
    name: 'Bibliothèque de Hull',
    type: 'public',
    province: 'QC',
    region: 'Gatineau',
    address: '15 Rue Victoria',
    city: 'Gatineau',
    postalCode: 'J8X 2A1',
    phone: '819-595-7460',
    website: 'https://www.gatineau.ca/portail/default.aspx?p=reseau_biblio/bibliotheques/hull',
    latitude: 45.4276,
    longitude: -75.7156
  },
  {
    id: 'little-toronto-2',
    name: 'Little Free Library - Kensington Market',
    type: 'little',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: 'Kensington Avenue at Dundas Street',
    city: 'Toronto',
    postalCode: 'M5T 1L7',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 43.6533,
    longitude: -79.4005
  },
  {
    id: 'little-calgary-1',
    name: 'Little Free Library - Inglewood',
    type: 'little',
    province: 'AB',
    region: 'Calgary',
    address: '9th Avenue SE',
    city: 'Calgary',
    postalCode: 'T2G 0R9',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 51.0456,
    longitude: -114.0338
  },
  {
    id: 'little-ottawa-1',
    name: 'Little Free Library - The Glebe',
    type: 'little',
    province: 'ON',
    region: 'Ottawa',
    address: 'Third Avenue near Bank Street',
    city: 'Ottawa',
    postalCode: 'K1S 2K1',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 45.4021,
    longitude: -75.6904
  },
  {
    id: 'little-montreal-1',
    name: 'Little Free Library - Mile End',
    type: 'little',
    province: 'QC',
    region: 'Montreal',
    address: 'Rue Saint-Viateur near Avenue du Parc',
    city: 'Montreal',
    postalCode: 'H2T 1A8',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 45.5234,
    longitude: -73.6004
  },
  {
    id: 'little-halifax-1',
    name: 'Little Free Library - North End Halifax',
    type: 'little',
    province: 'NS',
    region: 'Halifax',
    address: 'Gottingen Street',
    city: 'Halifax',
    postalCode: 'B3K 3B5',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 44.6629,
    longitude: -63.5876
  },
  {
    id: 'ualberta-library',
    name: 'University of Alberta Libraries',
    type: 'private',
    province: 'AB',
    region: 'Edmonton',
    address: '11204 Saskatchewan Drive NW',
    city: 'Edmonton',
    postalCode: 'T6G 2J8',
    phone: '780-492-3790',
    website: 'https://www.library.ualberta.ca/',
    latitude: 53.5232,
    longitude: -113.5263
  },
  {
    id: 'ucalgary-library',
    name: 'University of Calgary Libraries',
    type: 'private',
    province: 'AB',
    region: 'Calgary',
    address: '2500 University Drive NW',
    city: 'Calgary',
    postalCode: 'T2N 1N4',
    phone: '403-220-5110',
    website: 'https://library.ucalgary.ca/',
    latitude: 51.0799,
    longitude: -114.1311
  },
  {
    id: 'usask-library',
    name: 'University of Saskatchewan Library',
    type: 'private',
    province: 'SK',
    region: 'Saskatoon',
    address: '3 Campus Drive',
    city: 'Saskatoon',
    postalCode: 'S7N 5A4',
    phone: '306-966-5924',
    website: 'https://library.usask.ca/',
    latitude: 52.1310,
    longitude: -106.6333
  },
  {
    id: 'carleton-library',
    name: 'Carleton University Library',
    type: 'private',
    province: 'ON',
    region: 'Ottawa',
    address: '1125 Colonel By Drive',
    city: 'Ottawa',
    postalCode: 'K1S 5B6',
    phone: '613-520-2600',
    website: 'https://library.carleton.ca/',
    latitude: 45.3875,
    longitude: -75.6972
  },
  {
    id: 'uottawa-library',
    name: 'University of Ottawa Library',
    type: 'private',
    province: 'ON',
    region: 'Ottawa',
    address: '65 University Private',
    city: 'Ottawa',
    postalCode: 'K1N 9A5',
    phone: '613-562-5213',
    website: 'https://biblio.uottawa.ca/',
    latitude: 45.4229,
    longitude: -75.6831
  },
  {
    id: 'concordia-library',
    name: 'Concordia University Library',
    type: 'private',
    province: 'QC',
    region: 'Montreal',
    address: '1455 De Maisonneuve Boulevard West',
    city: 'Montreal',
    postalCode: 'H3G 1M8',
    phone: '514-848-2424',
    website: 'https://library.concordia.ca/',
    latitude: 45.4969,
    longitude: -73.5790
  },
  {
    id: 'ulaval-library',
    name: 'Bibliothèque Université Laval',
    type: 'private',
    province: 'QC',
    region: 'Quebec City',
    address: '2345 Allée des Bibliothèques',
    city: 'Quebec City',
    postalCode: 'G1V 0A6',
    phone: '418-656-3342',
    website: 'https://www.bibl.ulaval.ca/',
    latitude: 46.7817,
    longitude: -71.2761
  },
  {
    id: 'dalhousie-library',
    name: 'Dalhousie University Libraries',
    type: 'private',
    province: 'NS',
    region: 'Halifax',
    address: '6225 University Avenue',
    city: 'Halifax',
    postalCode: 'B3H 4R2',
    phone: '902-494-3601',
    website: 'https://libraries.dal.ca/',
    latitude: 44.6369,
    longitude: -63.5903
  },
  {
    id: 'umanitoba-library',
    name: 'University of Manitoba Libraries',
    type: 'private',
    province: 'MB',
    region: 'Winnipeg',
    address: '66 Chancellors Circle',
    city: 'Winnipeg',
    postalCode: 'R3T 2N2',
    phone: '204-474-9881',
    website: 'https://umanitoba.ca/libraries',
    latitude: 49.8089,
    longitude: -97.1364
  },
  {
    id: 'mun-qeii-library',
    name: 'Memorial University QEII Library',
    type: 'private',
    province: 'NL',
    region: "St. John's",
    address: 'Prince Philip Drive',
    city: "St. John's",
    postalCode: 'A1B 3Y1',
    phone: '709-864-7474',
    website: 'https://www.library.mun.ca/',
    latitude: 47.5719,
    longitude: -52.7348
  },
  {
    id: 'vpl-west-point-grey',
    name: 'West Point Grey Branch - Vancouver Public Library',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '4480 West 10th Avenue',
    city: 'Vancouver',
    postalCode: 'V6R 2H9',
    phone: '604-665-3970',
    website: 'https://www.vpl.ca/branches/west-point-grey-branch',
    latitude: 49.2634,
    longitude: -123.2088,
    services: ['wifi', 'printing', 'computers', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'burnaby-tommy-douglas',
    name: 'Tommy Douglas Library - Burnaby',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '7311 Kingsway',
    city: 'Burnaby',
    postalCode: 'V5E 1G8',
    phone: '604-436-5400',
    website: 'https://www.bpl.bc.ca/locations/tommy-douglas',
    latitude: 49.2263,
    longitude: -123.0104,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'richmond-brighouse',
    name: 'Brighouse Branch - Richmond Public Library',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '7700 Minoru Gate',
    city: 'Richmond',
    postalCode: 'V6Y 1R8',
    phone: '604-231-6413',
    website: 'https://yourlibrary.ca/brighouse',
    latitude: 49.1673,
    longitude: -123.1368,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'language-learning', 'accessibility', 'parking']
  },
  {
    id: 'surrey-city-centre',
    name: 'City Centre Library - Surrey',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '10350 University Drive',
    city: 'Surrey',
    postalCode: 'V3T 4C3',
    phone: '604-598-7323',
    website: 'https://www.surreylibraries.ca/locations/city-centre',
    latitude: 49.1867,
    longitude: -122.8490,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', 'language-learning', 'accessibility', 'parking', 'cafe']
  },
  {
    id: 'coquitlam-city-centre',
    name: 'City Centre Library - Coquitlam',
    type: 'public',
    province: 'BC',
    region: 'Metro Vancouver',
    address: '1169 Pinetree Way',
    city: 'Coquitlam',
    postalCode: 'V3B 8A9',
    phone: '604-937-4144',
    website: 'https://www.coqlibrary.ca/city-centre-library',
    latitude: 49.2789,
    longitude: -122.7935,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'nanaimo-harbourfront',
    name: 'Harbourfront Library - Nanaimo',
    type: 'public',
    province: 'BC',
    region: 'Vancouver Island',
    address: '90 Commercial Street',
    city: 'Nanaimo',
    postalCode: 'V9R 5G6',
    phone: '250-758-4697',
    website: 'https://virl.bc.ca/locations/harbourfront/',
    latitude: 49.1642,
    longitude: -123.9365,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'kelowna-central',
    name: 'Kelowna Branch - Okanagan Regional Library',
    type: 'public',
    province: 'BC',
    region: 'Okanagan',
    address: '1380 Ellis Street',
    city: 'Kelowna',
    postalCode: 'V1Y 9N3',
    phone: '250-762-2800',
    website: 'https://www.orl.bc.ca/kelowna',
    latitude: 49.8880,
    longitude: -119.4960,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'kamloops-downtown',
    name: 'Downtown Library - Thompson-Nicola Regional Library',
    type: 'public',
    province: 'BC',
    region: 'Kamloops',
    address: '465 Victoria Street',
    city: 'Kamloops',
    postalCode: 'V2C 2A9',
    phone: '250-372-5145',
    website: 'https://tnrl.ca/kamloops-downtown/',
    latitude: 50.6745,
    longitude: -120.3273,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'prince-george-central',
    name: 'Bob Harkins Branch - Prince George Public Library',
    type: 'public',
    province: 'BC',
    region: 'Prince George',
    address: '887 Dominion Street',
    city: 'Prince George',
    postalCode: 'V2L 5L1',
    phone: '250-563-9251',
    website: 'https://www.pgpl.ca/bob-harkins-branch',
    latitude: 53.9171,
    longitude: -122.7497,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'lethbridge-main',
    name: 'Lethbridge Public Library - Main Branch',
    type: 'public',
    province: 'AB',
    region: 'Lethbridge',
    address: '810 5 Avenue South',
    city: 'Lethbridge',
    postalCode: 'T1J 4C5',
    phone: '403-380-7310',
    website: 'https://www.lethlib.ca/main-library',
    latitude: 49.6938,
    longitude: -112.8410,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'red-deer-central',
    name: 'Red Deer Public Library',
    type: 'public',
    province: 'AB',
    region: 'Red Deer',
    address: '4818 49th Street',
    city: 'Red Deer',
    postalCode: 'T4N 6K8',
    phone: '403-346-4576',
    website: 'https://www.rdpl.org/',
    latitude: 52.2681,
    longitude: -113.8117,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'medicine-hat-main',
    name: 'Medicine Hat Public Library',
    type: 'public',
    province: 'AB',
    region: 'Medicine Hat',
    address: '414 1st Street SE',
    city: 'Medicine Hat',
    postalCode: 'T1A 0A8',
    phone: '403-502-8525',
    website: 'https://www.mhpl.ca/',
    latitude: 50.0368,
    longitude: -110.6717,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'mississauga-central',
    name: 'Mississauga Central Library',
    type: 'public',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '301 Burnhamthorpe Road West',
    city: 'Mississauga',
    postalCode: 'L5B 3Y3',
    phone: '905-615-3500',
    website: 'https://www.mississauga.ca/library/central-library/',
    latitude: 43.5890,
    longitude: -79.6441,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', 'accessibility', 'parking', 'cafe']
  },
  {
    id: 'brampton-four-corners',
    name: 'Four Corners Branch - Brampton Library',
    type: 'public',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '65 Queen Street East',
    city: 'Brampton',
    postalCode: 'L6V 1A2',
    phone: '905-793-4636',
    website: 'https://www.brampton.ca/en/residents/recreation/Pages/Libraries/Four-Corners-Branch-Library.aspx',
    latitude: 43.6832,
    longitude: -79.7613,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'language-learning', 'accessibility', 'parking']
  },
  {
    id: 'markham-central',
    name: 'Markham Public Library - Central',
    type: 'public',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '6031 Highway 7',
    city: 'Markham',
    postalCode: 'L3P 3A7',
    phone: '905-513-7977',
    website: 'https://www.markham.library.on.ca/central-library',
    latitude: 43.8561,
    longitude: -79.3370,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'windsor-central',
    name: 'Windsor Public Library - Central',
    type: 'public',
    province: 'ON',
    region: 'Windsor',
    address: '850 Ouellette Avenue',
    city: 'Windsor',
    postalCode: 'N9A 4M9',
    phone: '519-255-6770',
    website: 'https://www.windsorpubliclibrary.com/branch/central-library',
    latitude: 42.3149,
    longitude: -83.0364,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'barrie-centennial',
    name: 'Barrie Public Library - Centennial',
    type: 'public',
    province: 'ON',
    region: 'Barrie',
    address: '60 Worsley Street',
    city: 'Barrie',
    postalCode: 'L4M 1L6',
    phone: '705-728-1010',
    website: 'https://www.barrielibrary.ca/centennial',
    latitude: 44.3894,
    longitude: -79.6903,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'guelph-main',
    name: 'Guelph Public Library - Main',
    type: 'public',
    province: 'ON',
    region: 'Guelph',
    address: '100 Norfolk Street',
    city: 'Guelph',
    postalCode: 'N1H 4J6',
    phone: '519-824-6220',
    website: 'https://www.guelphpl.ca/en/locations/main-library.aspx',
    latitude: 43.5448,
    longitude: -80.2482,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'study-rooms', 'programs', 'children', 'digital-resources', 'makerspace', 'accessibility', 'parking']
  },
  {
    id: 'laval-centrale',
    name: 'Bibliothèque centrale de Laval',
    type: 'public',
    province: 'QC',
    region: 'Laval',
    address: '1535 Boulevard Chomedey',
    city: 'Laval',
    postalCode: 'H7V 3Z1',
    phone: '450-978-5959',
    website: 'https://www.bibliomulticulturelles.ca/centrale',
    latitude: 45.5585,
    longitude: -73.7321,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'sherbrooke-eva-senecal',
    name: 'Bibliothèque Éva-Senécal',
    type: 'public',
    province: 'QC',
    region: 'Sherbrooke',
    address: '535 Rue Marquette',
    city: 'Sherbrooke',
    postalCode: 'J1H 1M4',
    phone: '819-821-5886',
    website: 'https://www.biblio.sherbrooke.qc.ca/eva-senecal',
    latitude: 45.4042,
    longitude: -71.8929,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'trois-rivieres-gatien-lapointe',
    name: 'Bibliothèque Gatien-Lapointe',
    type: 'public',
    province: 'QC',
    region: 'Trois-Rivières',
    address: '1425 Place de l\'Hôtel-de-Ville',
    city: 'Trois-Rivières',
    postalCode: 'G9A 5P4',
    phone: '819-372-4611',
    website: 'https://www.v3r.net/loisirs/bibliotheque',
    latitude: 46.3432,
    longitude: -72.5478,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'longueuil-bienville',
    name: 'Bibliothèque de Bienville',
    type: 'public',
    province: 'QC',
    region: 'Longueuil',
    address: '2950 Rue de Beauharnois Est',
    city: 'Longueuil',
    postalCode: 'J4N 1A2',
    phone: '450-463-7100',
    website: 'https://www.longueuil.quebec/fr/bienville',
    latitude: 45.5598,
    longitude: -73.4680,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'brandon-main',
    name: 'Brandon Public Library',
    type: 'public',
    province: 'MB',
    region: 'Brandon',
    address: '638 Princess Avenue',
    city: 'Brandon',
    postalCode: 'R7A 0P3',
    phone: '204-727-6648',
    website: 'https://www.brandonlibrary.ca/',
    latitude: 49.8467,
    longitude: -99.9503,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'moose-jaw-main',
    name: 'Moose Jaw Public Library',
    type: 'public',
    province: 'SK',
    region: 'Moose Jaw',
    address: '461 Langdon Crescent',
    city: 'Moose Jaw',
    postalCode: 'S6H 0X6',
    phone: '306-692-2787',
    website: 'https://www.moosejawlibrary.ca/',
    latitude: 50.3933,
    longitude: -105.5519,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'sydney-cape-breton',
    name: 'Cape Breton Regional Library',
    type: 'public',
    province: 'NS',
    region: 'Sydney',
    address: '50 Falmouth Street',
    city: 'Sydney',
    postalCode: 'B1P 6J9',
    phone: '902-562-3161',
    website: 'https://www.cbrl.ca/',
    latitude: 46.1351,
    longitude: -60.1831,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility', 'parking']
  },
  {
    id: 'truro-colchester-east-hants',
    name: 'Colchester-East Hants Public Library - Truro',
    type: 'public',
    province: 'NS',
    region: 'Truro',
    address: '754 Prince Street',
    city: 'Truro',
    postalCode: 'B2N 1G8',
    phone: '902-895-4183',
    website: 'https://www.cehtrl.ca/truro',
    latitude: 45.3636,
    longitude: -63.2755,
    services: ['wifi', 'printing', 'computers', 'meeting-rooms', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'bathurst-public',
    name: 'Bathurst Public Library',
    type: 'public',
    province: 'NB',
    region: 'Bathurst',
    address: '256 King Avenue',
    city: 'Bathurst',
    postalCode: 'E2A 1P5',
    phone: '506-548-0830',
    website: 'https://www.gnb.ca/publiclibraries/bathurst',
    latitude: 47.6186,
    longitude: -65.6515,
    services: ['wifi', 'printing', 'computers', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'gander-public',
    name: 'Gander Public Library',
    type: 'public',
    province: 'NL',
    region: 'Gander',
    address: '4 Roe Avenue',
    city: 'Gander',
    postalCode: 'A1V 2E9',
    phone: '709-651-2935',
    website: 'https://www.nlpl.ca/branches/gander-public-library',
    latitude: 48.9569,
    longitude: -54.6089,
    services: ['wifi', 'printing', 'computers', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'grand-falls-windsor',
    name: 'Grand Falls-Windsor Public Library',
    type: 'public',
    province: 'NL',
    region: 'Grand Falls-Windsor',
    address: '39 High Street',
    city: 'Grand Falls-Windsor',
    postalCode: 'A2A 2J7',
    phone: '709-489-7402',
    website: 'https://www.nlpl.ca/branches/grand-falls-windsor-public-library',
    latitude: 48.9451,
    longitude: -55.6520,
    services: ['wifi', 'printing', 'computers', 'programs', 'children', 'digital-resources', 'accessibility']
  },
  {
    id: 'little-winnipeg-1',
    name: 'Little Free Library - Osborne Village',
    type: 'little',
    province: 'MB',
    region: 'Winnipeg',
    address: 'Osborne Street',
    city: 'Winnipeg',
    postalCode: 'R3L 2C1',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 49.8765,
    longitude: -97.1402
  },
  {
    id: 'little-saskatoon-1',
    name: 'Little Free Library - Broadway',
    type: 'little',
    province: 'SK',
    region: 'Saskatoon',
    address: 'Broadway Avenue',
    city: 'Saskatoon',
    postalCode: 'S7N 1B7',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 52.1220,
    longitude: -106.6687
  },
  {
    id: 'little-quebec-city-1',
    name: 'Little Free Library - Saint-Jean-Baptiste',
    type: 'little',
    province: 'QC',
    region: 'Quebec City',
    address: 'Rue Saint-Jean',
    city: 'Quebec City',
    postalCode: 'G1R 1P8',
    phone: 'N/A',
    website: 'https://littlefreelibrary.org/',
    latitude: 46.8118,
    longitude: -71.2194
  },
  {
    id: 'uwindsor-library',
    name: 'University of Windsor Leddy Library',
    type: 'private',
    province: 'ON',
    region: 'Windsor',
    address: '401 Sunset Avenue',
    city: 'Windsor',
    postalCode: 'N9B 3P4',
    phone: '519-253-3000',
    website: 'https://leddy.uwindsor.ca/',
    latitude: 42.3070,
    longitude: -83.0661
  },
  {
    id: 'western-library',
    name: 'Western University Libraries',
    type: 'private',
    province: 'ON',
    region: 'London',
    address: '1151 Richmond Street',
    city: 'London',
    postalCode: 'N6A 3K7',
    phone: '519-661-2111',
    website: 'https://www.lib.uwo.ca/',
    latitude: 43.0096,
    longitude: -81.2737
  },
  {
    id: 'york-university-library',
    name: 'York University Libraries',
    type: 'private',
    province: 'ON',
    region: 'Greater Toronto Area',
    address: '4700 Keele Street',
    city: 'Toronto',
    postalCode: 'M3J 1P3',
    phone: '416-736-5181',
    website: 'https://www.library.yorku.ca/',
    latitude: 43.7735,
    longitude: -79.5019
  },
  {
    id: 'uregina-library',
    name: 'University of Regina Library',
    type: 'private',
    province: 'SK',
    region: 'Regina',
    address: '3737 Wascana Parkway',
    city: 'Regina',
    postalCode: 'S4S 0A2',
    phone: '306-585-4400',
    website: 'https://www.uregina.ca/library/',
    latitude: 50.4186,
    longitude: -104.5689
  }
]

export function getLibraryStats() {
  const totalLibraries = libraries.length
  
  const byProvince = libraries.reduce((acc, lib) => {
    acc[lib.province] = (acc[lib.province] || 0) + 1
    return acc
  }, {} as Record<Province, number>)
  
  const byType = libraries.reduce((acc, lib) => {
    acc[lib.type] = (acc[lib.type] || 0) + 1
    return acc
  }, {} as Record<LibraryType, number>)
  
  return {
    total: totalLibraries,
    byProvince,
    byType
  }
}
